<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Lacertae.Domain\Lacertae.Domain.csproj" />
    <ProjectReference Include="..\Lacertae.Application\Lacertae.Application.csproj" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="CmlLib.Core" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" />
  </ItemGroup>
</Project>
