<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lacertae.Domain\Lacertae.Domain.csproj" />
    <ProjectReference Include="..\Lacertae.Application\Lacertae.Application.csproj" />
  </ItemGroup>
</Project>
