<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lacertae.Domain\Lacertae.Domain.csproj" />
    <ProjectReference Include="..\Lacertae.Application\Lacertae.Application.csproj" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
</Project>
